version: "3.3"

services:
  db:
    image: postgres
    networks:
      todo-net:
        aliases:
          - database
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - ./test_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: 111111
      POSTGRES_DB: "postgres"
      POSTGRES_ROOT_PASSWORD: 111111

  app:
    image: nikolaevfo/todo-app
    depends_on:
      - db
    ports:
      - "8000:8000"
    networks:
      - todo-net
    restart: always

  migrate:
    image: migrate/migrate
    depends_on:
      - db
      - app
    networks:
      - todo-net
    volumes:
      - ./schema:/migrations
    command:
      [
        "-path",
        "/migrations",
        "-database",
        "postgres://postgres:111111@database:5432/postgres?sslmode=disable",
        "up"
      ]
    links:
      - db


networks:
  todo-net:
